### ISSUE TITLE
Target triple question

### ISSUE THREAD

**Issue by KerryRJ** [ivmarkov/rust#2]
I would like to know if the target triple's should not be added e.g. xtensalx6-espressif-freertos-elf, esp32-espressif-freertos-elf or esp32-unknown-idf-elf rather than modifying the existing xtensa-esp32-none-elf triples?

I think that if the esp-rs changes are eventually up streamed or vice-versa then your/their target triple changes would clash with each other requiring separate triples.

**Comment by ivmarkov** [comment]
In the meantime, there is fortunately no more "mine" vs "theirs". There is now a single [Rust compiler fork for Espressif chips](https://github.com/esp-rs/rust) hosted in the esp-rs organization, which is having my Rust libstd changes merged.

This compiler fork here is therefore no more so important. It will remain just as a playground for myself only, before I upstream changes into the esp-rs compiler. Please switch to the esp-rs one. :)

As for having separate targets for "bare metal" vs "esp-idf/libstd" - you can have it with a single set of targets as well. Yet, in the end we decided to have separate targets because this is what the Rust mainline compiler itself follows:
* Bare metal `xtensa-esp32-none-elf` and base metal `xtensa-esp32s2-none-elf` (the bare metal ones for esp32cXX chips are already in Rust mainline as esp32cxx is riscv based, which is an officially supported architecture)
* esp-idf (or "OS" if you wish) ones:
  * `xtensa-esp32-espidf`
  * `xtensa-esp32s2-espidf`
  * `riscvimac-esp-espidf` - a single target for all esp32cxx chips
